# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: tests

on:
  push:
    branches:
      - develop 
      - master
  pull_request:
    branches:
      - develop 
      - master
  
jobs:
  test:
    env:
      PROTO_VERSION: ${{ secrets.PROTO_VERSION }}
      PROTO_PUBLIC_KEY: ${{ secrets.PROTO_PUBLIC_KEY }}
      PROTO_CLIENT_HASH: ${{ secrets.PROTO_CLIENT_HASH }}
      PROTO_SERVER_ADDRESS: ${{ secrets.PROTO_SERVER_ADDRESS }}
      PROTO_SERVER_PORT: ${{ secrets.PROTO_SERVER_PORT }}
      # MYSQL
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_USER: ${{ secrets.MYSQL_USER }}
      MYSQL_PASS: ${{ secrets.MYSQL_PASS }}
      # POSTGRES
      POSTGRE_DATABASE: ${{ secrets.POSTGRE_DATABASE }}
      POSTGRE_HOST: ${{ secrets.POSTGRE_HOST }}
      POSTGRE_PORT: ${{ secrets.POSTGRE_PORT }}
      POSTGRE_USER: ${{ secrets.POSTGRE_USER }}
      POSTGRE_PASSWORD: ${{ secrets.POSTGRE_PASSWORD }}
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Poetry Install dependencies
        uses: knowsuchagency/poetry-install@v1
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Test with pytest
        run: |
          poetry run pytest
